name: 'Release'

on:
  workflow_run:
    workflows: ["CICD"]
    types: [completed]
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
    branches: [ 'main', 'release/*', 'feature/*' ]

run-name: 'Release ALAppExtension to NuGet'

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

defaults:
  run:
    shell: PowerShell

jobs:
  Deliver:
      runs-on: [ windows-latest ]
      name: Deliver to Nuget.Org
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            path: '${{ github.workspace }}\.artifacts'

        - name: Publish artifacts
          uses: actions/upload-artifact@v3
          with:
            name: 'ALAppExtension'
            path: '${{ github.workspace }}\.artifacts\'
            retention-days: 1